version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      TZ: America/Recife
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - efs:/var/www/html
    environment:
      TZ: America/Recife
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: teste
      WORDPRESS_DB_PASSWORD: teste
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge

volumes:
  efs:
    driver: efs
    driver_opts:
      type: nfs
      o: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
      device: "fs-0deae370ba136fba4.efs.us-east-1.amazonaws.com:/"
